import { Component, OnInit } from '@angular/core';
import { AddressService } from '../services/address.service';
import { LoanService } from '../services/loan.service';
import { UserService } from '../services/user.service';
import { VehicleService } from '../services/vehicle.service';

@Component({
  selector: 'app-allapplicants',
  templateUrl: './allapplicants.component.html',
  styleUrls: ['./allapplicants.component.css']
})
export class AllapplicantsComponent implements OnInit {

  applicantDetails = null;
  loanDetails: any;
  vehicleDetails = null;
  addressDetails = null;

  constructor(private userService: UserService, private loanService: LoanService, private vehicleService: VehicleService, private addressService: AddressService) {
    this.getAllApplicants();
    this.getAllVehicles();
    this.getAllLoans();
    this.getAllAddress();
  }

  ngOnInit(): void {
  }

  getAllApplicants() {
    this.userService.getAllApplicants().subscribe(
      (res) => {
        this.applicantDetails = res;
      })
  }

  getAllAddress() {
    this.addressService.getAllAddress().subscribe(
      (res) => {
        this.addressDetails = res;
      }
    )
  }

  getAllVehicles() {
    this.vehicleService.getAllVehicles().subscribe(
      (res) => {
        this.vehicleDetails = res;
      })
  }

  getAllLoans() {
    this.loanService.getAllLoans().subscribe(
      (res) => {
        this.loanDetails = res;
      })
  }

  onApprove(id: number, loan: any) {
    // for updating loan, we will add new loan with the updated values
    // we are doing this because loanId is autogenerated
    loan.loanStatus = "Approved";
    console.log(loan);
    this.loanService.addLoan(loan).subscribe(
      (res) => {
        this.loanDetails = res;
        console.log(this.loanDetails);
      }
    )
    alert("Loan Approved!");
  }

  onReject(id: number, loan: any) {
    loan.loanStatus = "Rejected";
    console.log(loan);
    this.loanService.addLoan(loan).subscribe(
      (res) => {
        this.loanDetails = res;
      }
    )
    alert("Loan Rejected!");
  }
}
